twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        CartService: '@App\Service\CartService'
        StarService: '@App\Service\StarService'


when@test:
    twig:
        strict_variables: true

